Repository academiadev-jlle/backend-thunderpets, pull requests merged in 2018-12, with the labels that each got.

#44 Feature/8 Services | Mappers | Tests
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/dto/PetDTO.java
  src/main/java/br/com/academiadev/thunderpets/mapper/PetMapper.java
  src/main/java/br/com/academiadev/thunderpets/repository/FotoRepository.java
  src/main/java/br/com/academiadev/thunderpets/service/PetService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/PetServiceImpl.java
  src/main/resources/application-test.properties
  src/test/java/br/com/academiadev/thunderpets/controller/PetControllerTest.java
  src/test/java/br/com/academiadev/thunderpets/mapper/ContatoMapperTests.java
  src/test/java/br/com/academiadev/thunderpets/mapper/PetMapperTest.java
  src/test/java/br/com/academiadev/thunderpets/mapper/UsuarioMapperTests.java
  src/test/java/br/com/academiadev/thunderpets/util/FotoUtil.java
  src/test/java/br/com/academiadev/thunderpets/util/LocalizacaoUtil.java
  src/test/java/br/com/academiadev/thunderpets/util/PetDTOUtil.java
  src/test/java/br/com/academiadev/thunderpets/util/PetUtil.java
  src/test/java/br/com/academiadev/thunderpets/util/Util.java
Labels: review

#46 Esqueci minha senha e redefinição de senha (#40)
  .circleci/config.yml
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/ThunderpetsApplication.java
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/model/Pet.java
  src/main/java/br/com/academiadev/thunderpets/model/RecuperarSenha.java
  src/main/java/br/com/academiadev/thunderpets/repository/RecuperarSenhaRepository.java
  src/main/java/br/com/academiadev/thunderpets/service/EmailService.java
  src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/EmailServiceImpl.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V0008__criacao_tabela_recuperar_senha.sql
  src/test/java/br/com/academiadev/thunderpets/controller/UsuarioControllerTests.java
  src/test/java/br/com/academiadev/thunderpets/mapper/UsuarioMapperTests.java
  src/test/java/br/com/academiadev/thunderpets/util/UsuarioDTOUtil.java
  src/test/java/br/com/academiadev/thunderpets/util/UsuarioUtil.java
Labels: review

#51 Hotfix
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/exception/ExceptionAdvice.java
  src/main/java/br/com/academiadev/thunderpets/exception/NaoPermitidoException.java
  src/main/java/br/com/academiadev/thunderpets/mapper/PetMapper.java
  src/main/java/br/com/academiadev/thunderpets/repository/FotoRepository.java
  src/main/java/br/com/academiadev/thunderpets/repository/PetRepository.java
  src/main/java/br/com/academiadev/thunderpets/service/PetService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/PetServiceImpl.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
  src/main/resources/db/migration/V0009__alterar_data_registro_texto.sql
  src/test/java/br/com/academiadev/thunderpets/controller/PetControllerTest.java
Labels: hotfix, refactor, review

#53 Correção da busca por localização (#48)
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/repository/PetRepository.java
  src/main/java/br/com/academiadev/thunderpets/service/PetService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/PetServiceImpl.java
Labels: review

#56 Upload de foto
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/dto/FotoDTO.java
  src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
Labels: enhancement, refactor, review

#50 Login com o Facebook
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/config/security/WebConfigSecurityAdapter.java
  src/main/java/br/com/academiadev/thunderpets/controller/AuthController.java
  src/main/java/br/com/academiadev/thunderpets/model/Usuario.java
  src/main/java/br/com/academiadev/thunderpets/service/FacebookService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/EmailServiceImpl.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/FacebookServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement, review

#59 Hotfix - alteração de senha
  src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
Labels: hotfix, review

#61 Hotfix - pesquisa case insensitive
  src/main/java/br/com/academiadev/thunderpets/service/impl/PetServiceImpl.java
Labels: hotfix, review

#62 Hotfix - url frontend
  src/main/java/br/com/academiadev/thunderpets/enums/Especie.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/PetServiceImpl.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
  src/main/resources/application.yml
  src/test/java/br/com/academiadev/thunderpets/util/PetDTOUtil.java
Labels: hotfix, review
