Repository academiadev-jlle/backend-thunderpets, pull requests merged in 2018-11, with the labels that each got.

#18 [Refactor/11] Refactoring do controller dos pets
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/dto/PetDTO.java
  src/main/java/br/com/academiadev/thunderpets/exception/PetNaoEncontradoException.java
  src/main/java/br/com/academiadev/thunderpets/mapper/PetMapper.java
  src/main/java/br/com/academiadev/thunderpets/model/Foto.java
  src/main/java/br/com/academiadev/thunderpets/repository/FotoRepository.java
  src/main/java/br/com/academiadev/thunderpets/repository/LocalizacaoRepository.java
  src/main/java/br/com/academiadev/thunderpets/repository/PetRepository.java
  src/test/java/br/com/academiadev/thunderpets/ThunderpetsApplicationTests.java
Labels: review

#17 CRUD de usuários
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/dto/ContatoDTO.java
  src/main/java/br/com/academiadev/thunderpets/dto/UsuarioDTO.java
  src/main/java/br/com/academiadev/thunderpets/exception/FotoNaoEncontradaException.java
  src/main/java/br/com/academiadev/thunderpets/exception/UsuarioNaoEncontradoException.java
  src/main/java/br/com/academiadev/thunderpets/mapper/ContatoMapper.java
  src/main/java/br/com/academiadev/thunderpets/mapper/UsuarioMapper.java
  src/main/java/br/com/academiadev/thunderpets/model/Usuario.java
  src/main/java/br/com/academiadev/thunderpets/repository/ContatoRepository.java
  src/main/java/br/com/academiadev/thunderpets/repository/UsuarioRepository.java
Labels: review

#21 Documentação do controller de pets
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
Labels: review

#23 Filtro de busca de pets
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/dto/PetDTO.java
Labels: review

#24 Autenticação
  .circleci/config.yml
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/config/security/AuthorizationServerConfig.java
  src/main/java/br/com/academiadev/thunderpets/config/security/ResourceServerConfig.java
  src/main/java/br/com/academiadev/thunderpets/config/security/WebConfigSecurityAdapter.java
  src/main/java/br/com/academiadev/thunderpets/controller/AuthController.java
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/mapper/ContatoMapper.java
  src/main/java/br/com/academiadev/thunderpets/model/Contato.java
  src/main/java/br/com/academiadev/thunderpets/model/Usuario.java
  src/main/java/br/com/academiadev/thunderpets/repository/UsuarioRepository.java
  src/main/resources/application.properties
  src/test/java/br/com/academiadev/thunderpets/controller/AuthControllerTests.java
Labels: enhancement, review

#25 Release 2
  .circleci/config.yml
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/config/security/AuthorizationServerConfig.java
  src/main/java/br/com/academiadev/thunderpets/config/security/ResourceServerConfig.java
  src/main/java/br/com/academiadev/thunderpets/config/security/WebConfigSecurityAdapter.java
  src/main/java/br/com/academiadev/thunderpets/controller/AuthController.java
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/dto/ContatoDTO.java
  src/main/java/br/com/academiadev/thunderpets/dto/PetDTO.java
  src/main/java/br/com/academiadev/thunderpets/dto/UsuarioDTO.java
  src/main/java/br/com/academiadev/thunderpets/enums/Categoria.java
  src/main/java/br/com/academiadev/thunderpets/enums/Especie.java
  src/main/java/br/com/academiadev/thunderpets/enums/Idade.java
  src/main/java/br/com/academiadev/thunderpets/enums/Sexo.java
  src/main/java/br/com/academiadev/thunderpets/enums/Status.java
  src/main/java/br/com/academiadev/thunderpets/enums/TipoContato.java
  src/main/java/br/com/academiadev/thunderpets/enums/TipoPet.java
  src/main/java/br/com/academiadev/thunderpets/exception/FotoNaoEncontradaException.java
  src/main/java/br/com/academiadev/thunderpets/exception/PetNaoEncontradoException.java
  src/main/java/br/com/academiadev/thunderpets/exception/UsuarioNaoEncontradoException.java
  src/main/java/br/com/academiadev/thunderpets/mapper/ContatoMapper.java
  src/main/java/br/com/academiadev/thunderpets/mapper/PetMapper.java
  src/main/java/br/com/academiadev/thunderpets/mapper/UsuarioMapper.java
  src/main/java/br/com/academiadev/thunderpets/model/Contato.java
  src/main/java/br/com/academiadev/thunderpets/model/Foto.java
  src/main/java/br/com/academiadev/thunderpets/model/Localizacao.java
  src/main/java/br/com/academiadev/thunderpets/model/Pet.java
  src/main/java/br/com/academiadev/thunderpets/model/Usuario.java
  src/main/java/br/com/academiadev/thunderpets/repository/ContatoRepository.java
  src/main/java/br/com/academiadev/thunderpets/repository/FotoRepository.java
  src/main/java/br/com/academiadev/thunderpets/repository/LocalizacaoRepository.java
  src/main/java/br/com/academiadev/thunderpets/repository/PetRepository.java
  src/main/java/br/com/academiadev/thunderpets/repository/UsuarioRepository.java
  src/main/java/br/com/academiadev/thunderpets/rest/HelloWorldEndpoint.java
  src/main/resources/application.properties
  src/test/java/br/com/academiadev/thunderpets/ThunderpetsApplicationTests.java
  src/test/java/br/com/academiadev/thunderpets/controller/AuthControllerTests.java
Labels: release, review

#29 Flyway
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/db/migration/V0001__criacao_tabela_usuario.sql
  src/main/resources/db/migration/V0002__criacao_tabela_contato.sql
  src/main/resources/db/migration/V0003__criacao_tabela_localizacao.sql
  src/main/resources/db/migration/V0004__criacao_tabela_pet.sql
  src/main/resources/db/migration/V0005__criacao_tabela_foto.sql
Labels: config, enhancement, review

#32 Configurando CORS
  src/main/java/br/com/academiadev/thunderpets/config/security/WebConfigSecurityAdapter.java
  src/main/resources/db/migration/V0001__criacao_tabela_usuario.sql
  src/main/resources/db/migration/V0002__criacao_tabela_contato.sql
  src/main/resources/db/migration/V0003__criacao_tabela_localizacao.sql
  src/main/resources/db/migration/V0004__criacao_tabela_pet.sql
  src/main/resources/db/migration/V0005__criacao_tabela_foto.sql
Labels: enhancement, hotfix, review

#28 Criação do Service, Mapper e Tests de Usuário e Contato
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/mapper/ContatoMapper.java
  src/main/java/br/com/academiadev/thunderpets/mapper/UsuarioMapper.java
  src/main/java/br/com/academiadev/thunderpets/repository/ContatoRepository.java
  src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
  src/test/java/br/com/academiadev/thunderpets/controller/UsuarioControllerTests.java
  src/test/java/br/com/academiadev/thunderpets/mapper/ContatoMapperTests.java
  src/test/java/br/com/academiadev/thunderpets/mapper/UsuarioMapperTests.java
  src/test/java/br/com/academiadev/thunderpets/util/Util.java
Labels: review

#38 Release 3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/br/com/academiadev/thunderpets/config/security/WebConfigSecurityAdapter.java
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/mapper/ContatoMapper.java
  src/main/java/br/com/academiadev/thunderpets/mapper/UsuarioMapper.java
  src/main/java/br/com/academiadev/thunderpets/repository/ContatoRepository.java
  src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/db/migration/V0001__criacao_tabela_usuario.sql
  src/main/resources/db/migration/V0002__criacao_tabela_contato.sql
  src/main/resources/db/migration/V0003__criacao_tabela_localizacao.sql
  src/main/resources/db/migration/V0004__criacao_tabela_pet.sql
  src/main/resources/db/migration/V0005__criacao_tabela_foto.sql
  src/test/java/br/com/academiadev/thunderpets/controller/UsuarioControllerTests.java
  src/test/java/br/com/academiadev/thunderpets/mapper/ContatoMapperTests.java
  src/test/java/br/com/academiadev/thunderpets/mapper/UsuarioMapperTests.java
  src/test/java/br/com/academiadev/thunderpets/util/Util.java
Labels: release, review

#37 Atualização de versões
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: hotfix, review

#39 Refatorações
  .circleci/config.yml
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/controller/UsuarioController.java
  src/main/java/br/com/academiadev/thunderpets/dto/ApiResponse.java
  src/main/java/br/com/academiadev/thunderpets/dto/ApiValidationErrors.java
  src/main/java/br/com/academiadev/thunderpets/dto/PetDTO.java
  src/main/java/br/com/academiadev/thunderpets/dto/UsuarioDTO.java
  src/main/java/br/com/academiadev/thunderpets/exception/ErroAoProcessarException.java
  src/main/java/br/com/academiadev/thunderpets/exception/ExceptionAdvice.java
  src/main/java/br/com/academiadev/thunderpets/exception/FotoNaoEncontradaException.java
  src/main/java/br/com/academiadev/thunderpets/exception/NaoEncontradoException.java
  src/main/java/br/com/academiadev/thunderpets/exception/PetNaoEncontradoException.java
  src/main/java/br/com/academiadev/thunderpets/exception/UsuarioNaoEncontradoException.java
  src/main/java/br/com/academiadev/thunderpets/mapper/PetMapper.java
  src/main/java/br/com/academiadev/thunderpets/model/Localizacao.java
  src/main/java/br/com/academiadev/thunderpets/model/Pet.java
  src/main/java/br/com/academiadev/thunderpets/model/Usuario.java
  src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
  src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
  src/main/resources/db/migration/V0003__criacao_tabela_localizacao.sql
  src/main/resources/db/migration/V0004__criacao_tabela_pet.sql
  src/main/resources/db/migration/V0006__adicionar_descricao_localizacao.sql
  src/main/resources/db/migration/V0007__adicionar_unique_email_usuario.sql
  src/test/java/br/com/academiadev/thunderpets/controller/UsuarioControllerTests.java
Labels: enhancement, refactor, review
